### PR TITLE
Changed version for select2 from 4.0.1 to 3.5.4 because of ZenstruckF…

### PR DESCRIPTION
**Pull request by ptsavdar**
…ormBundle incompatibility

### CODE REVIEW

**Comment by stefk** [comment]
@ptsavdar, the version constraint should be modified accordingly in the bower config file (https://github.com/claroline/FrontEndBundle/blob/master/bower.json#L31).

**Comment by ptsavdar** [comment]
@stefk , I've changed it. You can view my modifs in my fork https://github.com/ptsavdar/FrontEndBundle/blob/master/bower.json

**Comment by ngodfraind** [comment]
@stefk is it good to merge ?

**Comment by stefk** [comment]
@ngodfraind, yes. @ptsavdar, sorry, I forgot that the diff was truncated.

**Pull request merged**
